name: Events exercices

on:
  workflow_dispatch:

jobs:
  print-event:
    runs-on: ubuntu-latest

    steps:
      - name: Print the event that triggered this workflows
        run: |
          echo ${{ github.event_name }}

      - name: Print the current time
        run: |
          echo $(date)