name: Target for call from another workflows

on:
  repository_dispatch:
    types: [ MyCustomEventName ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print client payload
        run: |
          echo 'ParamA' is ${{github.event.client_payload.paramA }}
          echo 'boolean' is ${{github.event.client_payload.boolean }}