name: Runner Exo 1

on:
  push:

jobs:
  ruuner-1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: cd node-app
      - run: npm ci
      - run: npm run build
      - run: npm test