name: Call another workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository dispatch
        uses: Zaiddd/repository-dispatch
        with:
          # A repo scoped Github Personal Access Token
          token: ${{ secrets.REPO_PAT }}
          # A custom webhook event name
          event-type: MyCustomEventName
          client-payload: '{"myFirstJobEvent": "Zaid le meilleur dev"}'
          # JSON payload with extra information about the webhook event that your action or workflow may use.
